language: generic

dist: trusty

services:
  - docker

install:
  - docker pull lamtev/latex-build-tools

matrix:
  include:
    - env: LATEX_TEMPLATE="bachelor_thesis"
    - env: LATEX_TEMPLATE="coursework"
    - env: LATEX_TEMPLATE="presentation"
    - env: LATEX_TEMPLATE="report"

script:
  - chmod +x travis_build.sh
  - docker run -v $TRAVIS_BUILD_DIR:/latex_templates lamtev/latex-build-tools /bin/bash -c " cd latex_templates && . ./travis_build.sh && build_latex_template $LATEX_TEMPLATE "
